// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MeterReader.Models;
//
//    var authRequest = AuthRequest.FromJson(jsonString);

namespace MeterReader.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AuthRequest
    {
        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }

        [JsonProperty("applicationId")]
        public string ApplicationId { get; set; }
    }

    public partial class AuthRequest
    {
        public static AuthRequest FromJson(string json) => JsonConvert.DeserializeObject<AuthRequest>(json, MeterReader.Models.Converter.Settings);
    }
}
